language: objective-c
xcode_project: UnitTestSample.xcodeproj # path to your xcodeproj folder
xcode_scheme: UnitTestSample
before_script:
- ./scripts/travis/add-key.sh
after_script:
- ./scripts/travis/remove-key.sh
after_success:
- ./scripts/travis/testflight.sh
env:
  global:
  - APPNAME="UnitTestSample"
  - 'DEVELOPER_NAME="iPhone Distribution: GOKHAN AKER (YXJ86876C6)"'
  - PROFILE_UUID=Wildcard_development_profile
